<?php
return [
	'title' => 'Intellectual Property',
	'desc1' => '			<p>A companies’ trademark differentiates its products and services from others in their competing markets. Therefore, throughout time, the trademark has become the distinctive sign for all products and services, as well as an information system for consumers regarding the origin and quality of such products and services. In that sense, a companies’ trademark has become a priceless intangible asset.</p>
							<p>The registration of a trademark, distinctive sign or commercial name provides the exclusive use of such elements by its registered owner. The exclusive use of such trademarks, distinctive signs and commercial names determines that any other company who wishes to use such marks needs prior consent from the registered owner.</p>
							<p>Furthermore, the registration of an invention patent, or any other type of patent entitles its registered owner the exclusive use of such patent for a 20 year period, hindering its use by other companies without express consent of the registered owner.</p>
							<p>Our law firm offers legal counsel in the registration of an industrial property right, such as Invention Patents, Utility Models, Industrial Designs, Industrial Secrets, Commercial Names, Commercial Slogans, Certification Trademarks, Trademarks (including service and product), Joint Trademarks and Protective Certificates for Domain and Origin Names. Additionally, we offer legal counsel in the renewal of trademark and commercial name licenses, the registration of assigned industrial property, exclusive usage of licenses and any other distinctive sign that requires registration.</p>
							<p>Also, we represent our clients in proceedings before the National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI),  regarding complaints filed against the use of similar and identical trademarks, cancellation of trademarks due to misuse, proceedings derived from breach of intellectual property regulations, annulment proceedings and any other proceeding regarding such matters.</p>
							<p class="text-bold">Copyright Law</p>
							<p>Our law firm offers legal counsel throughout the entire registration process of such works, as well as edition agreements, theatrical representation and musical execution agreements, phono-graphical Agreements, broadcasting agreements, amongst others.</p>
							<p>Our lawyers represent our clients in proceedings before the National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI), which are initiated due to breaches of the copyrights law regulations.</p>',
];