<?php
return [
	'title' => 'White Collar Crime',
	'desc' => '				<p>Our criminal law practice has earned a considerable amount of recognition in the Peruvian legal market due to the degree of specialization we have on white-collar criminal matters. We have obtained this by bringing together a team of dedicated professionals with outstanding academic credentials and a proven track record of participation in high-profile criminal cases.</p>

							<p>In terms of white-collar litigation, during the last decade our firm has been responsible for providing assistance in a wide variety of cases of national and economic importance. One of these was the criminal process associated with the government rescue of the Wiese Bank in which we were hired by JP Morgan in order to represent their Regional Director & Vice-president for the Andean Region, Central America and the Caribbean who had been unjustly brought under investigation.  We were also responsible for representing on of Peru’s largest media companies (Compañia de Radiodifusión – Canal 4) when charges were brought against former shareholders and board members who were being held responsible for over 80 million dollars as part of a reparation requested within the criminal process.  Thanks to our work in implementing a successful defense strategy tailored to the specifics of the case we managed not only to ensure our clients did not have to pay anything at all but also to obtain a sentence from the Supreme Court of Justice which set a binding precedent for all future cases of the same nature.</p>

							<p>In 2016 we decided to integrate our practice to the Rebaza, Alcázar y De Las Cases Law Firm completing a merger which had no precedents in the Peruvian legal market.  It was the first time a premier White-Collar Criminal Litigation practice joined a firm specializing in Finance & Corporate law matters creating a unique synergy in benefit of all its clients. This integration process has allowed us to strengthen the quality of our services by being able to count with the support of in-house professionals on the areas of financial law, corporate law, and tax law amongst others for the creation of comprehensive criminal defense strategies.</p>

							<p>When it comes to consultancy work we combine high-quality traditional services with innovative practices in criminal prevention programs for businesses (Criminal Compliance) related to crimes such as money laundering, financing of terrorism and bribing of government officials.  This has become a necessity due to the fact that recent legislative changes have introduced the administrative responsibility (in reality criminal) of legal persons.</p>

							<p>Some of our principal clients include: Banco de Crédito del Perú, Banco Internacional (INTERBANK), Banco Financiero, Compañía Peruana de Radiodifusión (CPR), Deloitte Perú, Editora El Comercio, Diario Perú 21, Electrolux del Perú, Pesquera Exalmar, Ezentis Perú,  Grupo Sandoval, Grupo Brescia, Glencore, Hipermercados Tottus, Inca Rail, JP Morgan, Quimpac, Messer Gases del Perú, Price Waterhouse Cooper, Pedro Pablo Kuczynski Goddard, Plantaciones de Ucayali, Prensa Popular, Repsol YPF, Saga Falabella, Sigma Safi, Statkraft, Telefónica del Perú, Trust, Vencorp, Instituto Peruano del Deporte, Organismo de Supervisión de Contrataciones del Estado, Grupo OBRAINSA.</p>',
];