<?php
return [
	'title' => 'Corporate Reorganization and Bankruptcy',
	'text' => '<p>The corporate reorganization and bankruptcy area of our law firm has experience in private corporate reorganizations, bankruptcy proceedings and corporate liquidations, as well as private agreements with creditors and the acquisition and sale of debt involved in insolvency of bankruptcy proceedings (creditos concursales). Our lawyers complement their practice with vast professional experience, offering our clients coherent and innovative solutions; combining financial, bankruptcy, corporate, banking, tax and labor regulations for comprehensive solutions.</p>
		<p>Regarding financial reorganization proceedings, our practice includes counseling on bankruptcy proceedings before the National Institute for the Defense of Competition and Protection of Intellectual Property (INDECOPI), as well as private proceedings where INDECOPI is not involved. Our practice is aimed towards counseling debtors and creditors in the reorganization process of liabilities of distressed companies. This is done through accurate and satisfactory counseling, emphasizing such solutions to the nature of the corporate crisis involved.</p>
		<p>Furthermore, our corporate reorganization area designs crisis buyout strategies for the acquisition and trade of such corporations, as well as portfolio acquisition, credit recovery, total and partial liability assignments and productive units. In this regard, our lawyers have the ability to work not only with the current bankruptcy regulations, but also with corporate and financial regulations, achieving complete and comprehensive solutions for our clients.</p>
		<p>Our law firm has experience on issues such as creditors meeting agreement impeachments, acknowledgment of credits and impeachment of such credits.</p>
		<p>It is worth mentioning that several mandatory administrative precedents (Precedentes de Observancia Obligatoria) before INDECOPI regarding bankruptcy and insolvency proceedings, under which INDECOPI has issued verdict on, have been motivated by the legal defense strategy of our lawyers.</p>
		<p>Finally, our area has constantly counseled corporations and banks that require our expertise on incidental matters regarding reorganization of assets and liquidation of bankrupt corporations, cooperating with such clients through specific and prompt assistance in operations where the counsel of experts is required.</p>'
];