<?php
return [
	'title' => 'Reestructuración e Insolvencias Empresariales',
	'text' => '<p>El área de reestructuración e insolvencias empresariales de nuestro Estudio tiene experiencia en procesos privados y concursales de reorganización y liquidación empresarial, así como en temas relacionados a la negociación y manejo de operaciones de adquisición y venta de créditos concursales y de empresas con dificultades financieras. Nuestros abogados complementan entre sí su trabajo y experiencia profesional, otorgándole a la misma una visión integral del problema, ofreciendo al cliente soluciones coherentes e innovadoras; combinando para ello aspectos financieros, concursales, societarios, bancarios, tributarios y laborales.</p>
		<p>En el ámbito de los procesos de reorganización financiera, nuestras actividades se desarrollan tanto fuera como dentro del marco de los procedimientos concursales. Nuestra experiencia se orienta a asesorar tanto a deudores como acreedores en los procesos de reestructuración integral de pasivos de la empresa en dificultades financieras y patrimoniales, formulando soluciones adecuadas y satisfactorias para la naturaleza de la crisis empresarial.</p>
		<p>Asimismo, nuestra área presta servicios de asesoría en el diseño de estrategias para la adquisición y venta de empresas en concurso o en crisis, compra de cartera, recuperación de créditos, cesiones globales de activo y pasivo y unidades productivas; etc. Para ello, no sólo se vale de los medios que nuestra legislación concursal otorga, sino también de los medios que nuestra legislación societaria y financiera permite.</p>
		<p>También tenemos experiencia en impugnación de acuerdos de Junta de Acreedores, reconocimiento de créditos e impugnación de estos últimos.</p>
		<p>Vale la pena destacar que, varios de los Precedentes de Observancia obligatoria que ha emitido el Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual –Indecopi- en materia concursal, han sido motivados por la defensa realizada por nuestros abogados en casos concretos.</p>
		<p>Finalmente es importante señalar que nuestra área constantemente es consultada por empresas y bancos que requieren una asesoría eventual en el área de reestructuración patrimonial y disolución y liquidación de empresas en concurso, colaborando por ello en aspectos muy puntuales y específicos en los que se requiere de expertos profesionales en la materia.</p>'
];